######################################################################
##
## Filename: pc.udo
## Created on: Fri Sep 21 12:59:41 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
