######################################################################
##
## Filename: tb_cpu.udo
## Created on: Sat Sep 29 21:42:13 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
