######################################################################
##
## Filename: tb_processor.udo
## Created on: Fri Sep 28 15:04:08 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
