######################################################################
##
## Filename: tb_cpu.udo
## Created on: Wed Oct 10 19:21:15 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
